version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-qa
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploaded_files:/app/uploaded_files  
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend-qa
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
